name: Trigger auto deployment for realtimemcp

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.REALTIMEMCP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REALTIMEMCP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REALTIMEMCP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Real-Time-MCP.FunctionApp/Dockerfile

          registryUrl: realitimemessagingacr-ewaxdbgtazcjcsh8.azurecr.io
          registryUsername: ${{ secrets.REALTIMEMCP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REALTIMEMCP_REGISTRY_PASSWORD }}

          containerAppName: realtimemcp
          resourceGroup: RES_Transactions

          imageToBuild: realitimemessagingacr-ewaxdbgtazcjcsh8.azurecr.io/realtimemcp:${{ github.sha }}